version: "3"
services:
  app:
    image: "janela/news"
    container_name: janela-news
    build:
      context: .
      dockerfile: "docker/${APP_SERVER}/Dockerfile"
    depends_on:
      - redis
      - mysql
    ports:
      - "7071:80"
      - "7072:443"
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    #restart: always

  redis:
    container_name: janela-news-redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data
    #restart: always

  scheduler:
    image: "janela/news"
    container_name: janela-news-scheduler
    depends_on:
      - app
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    #restart: always

  queue:
    image: "janela/news"
    container_name: janela-news-queue
    depends_on:
      - app
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    #restart: always

  mysql:
    container_name: janela-news-mysql
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    #restart: always

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
